### ISSUE TITLE
Allow extending of the linter configurations

### ISSUE THREAD

**Issue by mihaivilcuosf** [OSFGlobal/OSF-Linter#2]
Things to take into account:

- the goal would be to have a way to extend the existing rules
- have upgrade guides when a new version is released and the changes are not backwords compatible
  - some linters have tools to update the formatting of the files automatically
  - ways to disable the rule (if necessary)

**Comment by danechitoaie** [comment]
Updated the README with how to extend the configuration and override the config.
We'll also start adding release notes for each new release.
