### ISSUE TITLE
Integration with editors

### ISSUE THREAD

**Issue by mihaivilcuosf** [OSFGlobal/OSF-Linter#3]
We should have some documentation on how we can configure the editors to take into account the rules from this tool.
Usually they rely on a configuration file specific to the linter which is in the root of the project.

**Comment by ClaudiuCudla** [comment]
And would this integration allow for developers to pre-check their code before submitting? Also maybe to be used as a pre-commit hook?

**Comment by danechitoaie** [comment]
Updated the README with how you can integrate with code editors.

And you can also add it as precomit hooks if you want. It would be same command that runs in Jenkins.
